Dropped ClosedStruct event (meta)data wrapping
It comes out that the way ClosedStruct works internally can cause issues
for some key names. The best example would be trying to initialize event
with `object_id` as data key.

    RubyEventStore::Event.new(data: { object_id: 42 })
    ArgumentError: Cannot define object_id as it already exists
    from /home/xxx/gems/closed_struct-0.1.0/lib/closed_struct.rb:9:in `block in initialize'

Same error will be raised for any key name which is the same as any of
the `Object` methods.

If users want to have object-like behavior, instead of hash-like for
events, they should implement it on their own.

Submitted issue: https://github.com/arkency/ruby_event_store/issues/33